const DEMO=[
{id:"demo-1",mode:"sale",title:"The Grand Modern",city:"Austin",state:"TX",price:895000,beds:4,baths:3,sqft:2840,type:"Single Family",tag:"FEATURED",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",description:"A refined modern residence with generous living areas and contemporary finishes."},
{id:"demo-2",mode:"sale",title:"Cedar Ridge Residence",city:"Atlanta",state:"GA",price:679000,beds:4,baths:3,sqft:2510,type:"Single Family",tag:"NEW",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",description:"A spacious family home in a sought-after Atlanta setting."},
{id:"demo-3",mode:"sale",title:"Oceanview House",city:"Miami",state:"FL",price:1250000,beds:5,baths:4,sqft:3380,type:"Single Family",tag:"LUXURY",image:"https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85",description:"A luxury Miami home designed for indoor-outdoor living."},
{id:"demo-4",mode:"rent",title:"Park Avenue Residence",city:"New York",state:"NY",price:6200,beds:2,baths:2,sqft:1260,type:"Apartment",tag:"RENT",image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85",description:"Elegant city apartment living in the heart of New York."},
{id:"demo-5",mode:"rent",title:"Westside Townhome",city:"Los Angeles",state:"CA",price:4800,beds:3,baths:2.5,sqft:1780,type:"Townhouse",tag:"RENT",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",description:"A comfortable Los Angeles townhome with modern space and privacy."},
{id:"demo-6",mode:"sale",title:"Hill Country Retreat",city:"Dallas",state:"TX",price:1125000,beds:5,baths:4,sqft:3650,type:"Single Family",tag:"LUXURY",image:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85",description:"A spacious Texas retreat with room for entertaining and everyday life."}
];
const params=new URLSearchParams(location.search);let mode=params.get("mode")==="rent"?"rent":"sale";let all=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function render(items){const g=document.querySelector("#propertyGrid"),e=document.querySelector("#propertyEmpty");if(!items.length){g.innerHTML="";e.classList.remove("hidden");return}e.classList.add("hidden");g.innerHTML=items.map(p=>`<article class="listing-card"><div class="listing-image" style="background-image:url('${esc(p.image)}')"><span class="badge">${esc(p.tag)}</span></div><div class="listing-info"><div class="price">$${Number(p.price||0).toLocaleString()}${mode==="rent"?"/mo":""}</div><div class="listing-title">${esc(p.title)}</div><div class="address">${esc(p.city)}, ${esc(p.state)}</div><div class="stats"><span>${esc(p.beds)} bd</span><span>${esc(p.baths)} ba</span><span>${Number(p.sqft||0).toLocaleString()} sq ft</span></div><div class="card-actions"><a class="primary" href="property.html?id=${encodeURIComponent(p.id)}&mode=${mode}">View Property</a><a href="#" class="property-map" data-address="${esc(p.address||p.city+", "+p.state)}">Map</a></div></div></article>`).join("")}
async function load(){const type=params.get("type")||"";document.querySelector("#pageTitle").textContent=mode==="rent"?"Rental properties":"Homes for sale";document.querySelector("#pType").value=type;all=DEMO.filter(x=>x.mode===mode);try{const r=await fetch("/api/listings?mode="+mode+"&limit=24");const d=await r.json();if(Array.isArray(d.listings)&&d.listings.length)all=d.listings.map(p=>({...p,id:p.id||crypto.randomUUID(),mode,title:p.title||p.formattedAddress?.split(",")[0]||"EstateLux Property",city:p.city||"",state:p.state||"",price:p.price,beds:p.bedrooms??"—",baths:p.bathrooms??"—",sqft:p.squareFootage||0,type:p.propertyType||"Property",tag:p.listingType?.toUpperCase()||"PROPERTY",image:p.photo||p.photos?.[0]||DEMO[0].image,address:p.formattedAddress,description:p.description||""}))}catch(e){}filter()}
function filter(){const q=document.querySelector("#pLocation").value.trim().toLowerCase(),t=document.querySelector("#pType").value,b=document.querySelector("#pBeds").value;render(all.filter(p=>(!q||(p.city+" "+p.state+" "+p.title+" "+(p.address||"")).toLowerCase().includes(q))&&(!t||p.type===t)&&(!b||Number(p.beds)>=Number(b))))}
document.querySelector("#pSearch").addEventListener("click",filter);load();
document.addEventListener("click",e=>{const a=e.target.closest(".property-map");if(!a)return;e.preventDefault();const destination=a.dataset.address;if(!navigator.geolocation){alert("EstateLux needs your location to open directions. Please enable location in your browser.");return}navigator.geolocation.getCurrentPosition(pos=>{const origin=pos.coords.latitude+","+pos.coords.longitude;window.open("https://www.google.com/maps/dir/?api=1&origin="+encodeURIComponent(origin)+"&destination="+encodeURIComponent(destination),"_blank","noopener");},()=>alert("Please turn on location permission for EstateLux so we can open directions from your current location."),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})});
